[package]
name = "nusamai-projection"
version = "0.1.0"
edition = "2021"

[dependencies]
japan-geoid = { git = "https://github.com/MIERUNE/japan-geoid" }
lz4_flex = "0.11.1"
rust-embed = "8.0.0"
thiserror = "1.0.50"
